name: GeyserDamageTooltipFix
version: '${project.version}'
main: me.jacob.damagetooltipfix.GeyserDamageTooltipFix
author: Jacob
description: Fixes the damage tooltip for Bedrock players on a Java server using Geyser
depend: [floodgate, ProtocolLib]
api-version: 1.18

commands:
  reloaddamagetooltipfix:
    description: Reloads the config
    usage: /reloaddamagetooltipfix
